//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod prelude;

pub mod tbl_address;
pub mod tbl_contact;
pub mod tbl_contact_type;
pub mod tbl_staff;
pub mod tbl_staff_address;
pub mod tbl_staff_contract;
pub mod tbl_staff_type;
