//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "cls_staff", table_name = "tbl_contact_type")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub contact_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tbl_contact::Entity")]
    TblContact,
    #[sea_orm(has_many = "super::tbl_staff_contract::Entity")]
    TblStaffContract,
}

impl Related<super::tbl_contact::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContact.def()
    }
}

impl Related<super::tbl_staff_contract::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblStaffContract.def()
    }
}

impl Related<super::tbl_staff::Entity> for Entity {
    fn to() -> RelationDef {
        super::tbl_staff_contract::Relation::TblStaff.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::tbl_staff_contract::Relation::TblContactType
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
