//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "cls_staff", table_name = "tbl_contact")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub contact_type_id: Uuid,
    pub contact_value: String,
    pub tenant_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tbl_contact_type::Entity",
        from = "Column::ContactTypeId",
        to = "super::tbl_contact_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TblContactType,
    #[sea_orm(has_many = "super::tbl_staff_contact::Entity")]
    TblStaffContact,
}

impl Related<super::tbl_contact_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblContactType.def()
    }
}

impl Related<super::tbl_staff_contact::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TblStaffContact.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
