//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::tbl_address::Entity as TblAddress;
pub use super::tbl_contact::Entity as TblContact;
pub use super::tbl_contact_type::Entity as TblContactType;
pub use super::tbl_staff::Entity as TblStaff;
pub use super::tbl_staff_address::Entity as TblStaffAddress;
pub use super::tbl_staff_contact::Entity as TblStaffContact;
pub use super::tbl_staff_type::Entity as TblStaffType;
